[tool.black]
extend-exclude = "src/pokemanki/libaddon/"

[tool.isort]
profile = "black"
extend_skip = [
    "src/pokemanki/libaddon/",
    "src/pokemanki/gui/forms/",
]

[tool.mypy]
exclude = [
    "src/pokemanki/libaddon/",
]
