name: check-code
run-name: Check ${{ github.event_name }} by @${{ github.actor }}

on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check"
          src: "./src/pokemanki"
