name: check-version
run-name: Check tag ${{ github.ref_name }} pushed by @${{ github.actor }}

on:
  push:
    tags:
      - '*'

jobs:
  compare:
    name: Compare version of tag and code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Read _version.py
        id: code-version
        uses: juliangruber/read-file-action@v1
        with:
          path: "./src/pokemanki/_version.py"
      - name: Compare tag with code version
        run: |
          echo "${{ steps.code-version.outputs.content }}" | grep __version__ | sed 's/__version__ = "\([[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+\)"/\1/' > $CODE_VERSION
          echo "${{ github.ref_name }}" | sed 's/v\([[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+\)/\1/' > $TAG_VERSION
          if [ "$TAG_VERSION" = "$CODE_VERSION" ]; then
            echo "Version valid and matching" | tee -a $GITHUB_STEP_SUMMARY
          else
            echo "Version invalid or mismatched in tag and code" | tee -a $GITHUB_STEP_SUMMARY
            exit 1
          fi
